import Head from 'next/head'
import CustomLink from "../components/CustomLink";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Next-Test</title>
        <meta name="description" content="Generated by Georg" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <nav className="nav-bar">
            <CustomLink href={'/sw-character-client'}>/sw-character-client</CustomLink>
            <CustomLink href={'/sw-character-client/1'}>/sw-character-client/1</CustomLink>
            <hr/>
            <CustomLink href={'/sw-character-dynamic'}>/sw-character-dynamic</CustomLink>
            <CustomLink href={'/sw-character-dynamic/1'}>/sw-character-dynamic/1</CustomLink>
            <hr/>
            <CustomLink href={'/sw-character-static'}>/sw-character-static</CustomLink>
            <CustomLink href={'/sw-character-static/1'}>/sw-character-static/1</CustomLink>
            <hr/>
            <CustomLink href={'/planets/dorin'}>/planets/dorin</CustomLink>
        </nav>
      </main>
    </div>
  )
}
